apiVersion: apps/v1
kind: Deployment
metadata:
  name: renata-backend-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: renata-backend-api
      env: dev
  template:
    metadata:
      labels:
        app: renata-backend-api
        env: dev
    spec:
      containers:
      - name: renata-backend-api
        image: GAR_LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:GITHUB_SHA
        imagePullPolicy: Always
        ports:
        - containerPort: 3000

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: renata-backend-api
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: renata-backend-api
  targetCPUUtilizationPercentage: 80

---

apiVersion: v1
kind: Service
metadata:
  name: renata-backend-api-service
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
  selector:
    app: renata-backend-api
