apiVersion: v1
kind: ConfigMap
metadata:
  name: renata-backend-api-configmap
data:
  key.json: |
    ENV_GOOGLE_SERVICE_UP_AVATAR_KEY
  jwt_secret_key: |
    ENV_JWT_SECRET_KEY
  google_cloud_project_id: |
    ENV_GOOGLE_CLOUD_PROJECT_ID
  google_cloud_storage_bucket: |
    ENV_GOOGLE_CLOUD_STORAGE_BUCKET
  google_email: |
    ENV_GOOGLE_EMAIL
  google_refresh_token: |
    ENV_GOOGLE_REFRESH_TOKEN
  google_redirect_uri: |
    ENV_GOOGLE_REDIRECT_URI
  google_client_secret: |
    ENV_GOOGLE_CLIENT_SECRET
  google_client_id: |
    ENV_GOOGLE_CLIENT_ID
  db_dialect_dev: |
    ENV_DB_DIALECT_DEV
  db_port_dev: |
    ENV_DB_PORT_DEV
  db_host_dev: |
    ENV_DB_HOST_DEV
  db_name_dev: |
    ENV_DB_NAME_DEV
  db_password_dev: |
    ENV_DB_PASSWORD_DEV
  db_username_dev: |
    ENV_DB_USERNAME_DEV
  port: |
    ENV_PORT
